import { BusinessConfig } from '@/types'
import dynamicConfigs from './dynamicConfigs.json'

const STATIC_CONFIGS: Record<string, BusinessConfig> = {
  pixelpub: {
    id: 'pixelpub',
    name: 'PixelPub',
    type: 'gaming_pub',
    tagline: 'Play More. Earn More.',
    currency: { name: 'Tokens', symbol: 'T' },
    primaryColor: '#7C3AED',
    accentColor: '#F59E0B',
    activities: [
      { id: 'daily_checkin', name: 'Daily check-in', points: 5, category: 'Visit', icon: '✅', description: 'Check in every day to build your streak' },
      { id: 'play_arcade', name: 'Play an arcade machine', points: 10, category: 'Gaming', icon: '🕹️', description: 'Any arcade cabinet counts' },
      { id: 'play_console', name: 'Console session (30+ min)', points: 12, category: 'Gaming', icon: '🎮', description: 'Grab a controller and play for at least 30 minutes' },
      { id: 'mini_game', name: 'Complete daily mini-game', points: 15, category: 'Gaming', icon: '🎯', description: 'Beat the in-app reaction challenge' },
      { id: 'visit_weekday', name: 'Visit Tuesday–Thursday', points: 25, category: 'Visit', icon: '📅', description: 'Earn bonus tokens on our quieter days' },
      { id: 'happy_hour', name: 'Visit during happy hour', points: 20, category: 'Visit', icon: '⏰', description: '5–7pm weekdays — double the fun, bonus tokens' },
      { id: 'quiz_night', name: 'Join quiz night', points: 30, category: 'Social', icon: '🧠', description: 'Every Wednesday at 8pm' },
      { id: 'bring_friends', name: 'Come with 3+ friends', points: 40, category: 'Social', icon: '👾', description: 'The more the merrier — and the more you earn' },
      { id: 'share_score', name: 'Share your high score', points: 10, category: 'Social', icon: '📢', description: 'Post on social and tag us for your tokens' },
      { id: 'stream_session', name: 'Stream your gameplay', points: 20, category: 'Social', icon: '📹', description: 'Go live from the pub and earn tokens' },
      { id: 'tournament_entry', name: 'Enter a tournament', points: 50, category: 'Competitive', icon: '🏆', description: 'Registered tournament entries earn big' },
      { id: 'win_tournament', name: 'Win a tournament', points: 150, category: 'Competitive', icon: '🥇', description: 'Top the leaderboard and take home the glory' },
      { id: 'refer_friend', name: 'Refer a friend', points: 100, category: 'Social', icon: '👥', description: 'They sign up, you both earn' },
      { id: 'birthday_visit', name: 'Visit on your birthday', points: 75, category: 'Special', icon: '🎂', description: 'Celebrate with us for a birthday token bonus' },
    ],
    rewards: [
      { id: 'console_priority', name: 'Priority Console Booking', cost: 75, icon: '🎮', description: 'Skip the queue and book your favourite console' },
      { id: 'free_token', name: '1 Free Gaming Token', cost: 100, icon: '🪙', description: 'One free play on any arcade machine' },
      { id: 'free_drink', name: 'Free Soft Drink', cost: 150, icon: '🥤', description: 'Any soft drink at the bar on us' },
      { id: 'guest_pass', name: 'Bring a Guest Free', cost: 200, icon: '🎟️', description: 'One free entry for a friend on your next visit' },
      { id: 'tournament_free', name: 'Free Tournament Entry', cost: 250, icon: '🏆', description: 'Enter any upcoming tournament at no cost' },
      { id: 'merch_discount', name: '20% off PixelPub Merch', cost: 350, icon: '👕', description: 'Hoodies, tees, caps — discount applied at checkout' },
      { id: 'vip_night', name: 'VIP Tuesday Night Access', cost: 500, icon: '⭐', description: 'Reserved seating, dedicated console, one free drink' },
      { id: 'monthly_pass', name: '1-Month Unlimited Gaming', cost: 1200, icon: '♾️', description: 'Unlimited arcade and console play for a full month' },
    ],
    tiers: [
      { name: 'Rookie', minPoints: 0, color: '#9CA3AF' },
      { name: 'Player', minPoints: 250, color: '#10B981' },
      { name: 'Champion', minPoints: 600, color: '#F59E0B' },
      { name: 'Legend', minPoints: 1200, color: '#7C3AED' },
    ],
    aiPersonalisationEnabled: true,
  },
  dentalplus: {
    id: 'dentalplus',
    name: 'DentalPlus',
    type: 'dental_clinic',
    tagline: 'Healthy Habits. Bright Smiles.',
    currency: { name: 'SmilePoints', symbol: 'SP' },
    primaryColor: '#0EA5E9',
    accentColor: '#10B981',
    activities: [
      { id: 'brush_morning', name: 'Morning brush logged', points: 5, category: 'Daily', icon: '🌅', description: 'Log your morning brush — 2 minutes counts' },
      { id: 'brush_night', name: 'Night brush logged', points: 5, category: 'Daily', icon: '🌙', description: 'End the day right with your night brush' },
      { id: 'electric_brush', name: 'Electric toothbrush used', points: 8, category: 'Daily', icon: '⚡', description: 'Upgrade your routine for bonus points' },
      { id: 'floss', name: 'Flossing logged', points: 10, category: 'Daily', icon: '🧵', description: 'Floss daily — your gums will thank you' },
      { id: 'mouthwash', name: 'Mouthwash used', points: 5, category: 'Daily', icon: '💧', description: 'Finish your routine with a rinse' },
      { id: 'water_flosser', name: 'Water flosser logged', points: 8, category: 'Daily', icon: '💦', description: 'Hydro-clean between teeth for extra points' },
      { id: 'appointment', name: 'Attend your appointment', points: 100, category: 'Clinic', icon: '🦷', description: 'Show up and you\'ve already won' },
      { id: 'no_cancel', name: 'No-cancellation attendance', points: 30, category: 'Clinic', icon: '✓', description: 'Attend without cancelling in the previous 30 days' },
      { id: 'book_ahead', name: 'Book next appointment in-clinic', points: 20, category: 'Clinic', icon: '📋', description: 'Book before you leave — easiest points you\'ll earn' },
      { id: 'anxiety_checkin', name: 'Pre-appointment check-in', points: 15, category: 'Clinic', icon: '💬', description: 'Let us know how you\'re feeling before you arrive' },
      { id: 'oral_health_quiz', name: 'Complete oral health quiz', points: 20, category: 'Learning', icon: '📚', description: 'Test your dental knowledge — new quiz every month' },
      { id: 'tip_read', name: 'Read weekly oral health tip', points: 5, category: 'Learning', icon: '💡', description: 'One tip a week keeps cavities away' },
      { id: 'family_booking', name: 'Book for a family member', points: 25, category: 'Family', icon: '👨‍👩‍👧', description: 'Look after your whole family\'s smile' },
      { id: 'refer_patient', name: 'Refer a patient', points: 75, category: 'Social', icon: '🤝', description: 'They join, you both earn SmilePoints' },
    ],
    rewards: [
      { id: 'tip_pack', name: 'Premium Dental Care Pack', cost: 80, icon: '🎁', description: 'Toothpaste, floss, and mouthwash bundle' },
      { id: 'whitening_discount', name: '10% off teeth whitening', cost: 120, icon: '✨', description: 'Applied to your next whitening treatment' },
      { id: 'priority_booking', name: 'Priority booking slot', cost: 150, icon: '⚡', description: 'Choose any available slot, no wait list' },
      { id: 'family_discount', name: '10% off family treatment', cost: 200, icon: '👨‍👩‍👧', description: 'Discount on any family member\'s next appointment' },
      { id: 'free_hygiene', name: 'Free hygiene clean', cost: 250, icon: '🪥', description: 'A full professional clean on us' },
      { id: 'whitening_kit', name: 'Take-home whitening kit', cost: 350, icon: '😁', description: 'Professional-grade kit to use at home' },
      { id: 'free_checkup', name: 'Free annual checkup', cost: 400, icon: '🦷', description: 'Full examination and X-rays included' },
    ],
    tiers: [
      { name: 'Starter', minPoints: 0, color: '#9CA3AF' },
      { name: 'Regular', minPoints: 150, color: '#10B981' },
      { name: 'Dedicated', minPoints: 400, color: '#0EA5E9' },
      { name: 'Champion', minPoints: 800, color: '#F59E0B' },
    ],
    aiPersonalisationEnabled: true,
  },
}

export const BUSINESS_CONFIGS: Record<string, BusinessConfig> = {
  ...STATIC_CONFIGS,
  ...(dynamicConfigs as Record<string, BusinessConfig>),
}
